/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

import { Route as rootRouteImport } from './routes/__root';
import { Route as ProfileRouteImport } from './routes/profile';

const SignupLazyRouteImport = createFileRoute('/signup')();
const LoginLazyRouteImport = createFileRoute('/login')();
const HomeLazyRouteImport = createFileRoute('/home')();
const CoderushLazyRouteImport = createFileRoute('/coderush')();
const IndexLazyRouteImport = createFileRoute('/')();
const CoderushGuess_outputSeedLazyRouteImport = createFileRoute(
  '/coderush/guess_output/$seed'
)();

const SignupLazyRoute = SignupLazyRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route));
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route));
const HomeLazyRoute = HomeLazyRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route));
const CoderushLazyRoute = CoderushLazyRouteImport.update({
  id: '/coderush',
  path: '/coderush',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/coderush.lazy').then((d) => d.Route));
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route));
const CoderushGuess_outputSeedLazyRoute =
  CoderushGuess_outputSeedLazyRouteImport.update({
    id: '/guess_output/$seed',
    path: '/guess_output/$seed',
    getParentRoute: () => CoderushLazyRoute,
  } as any).lazy(() =>
    import('./routes/coderush/guess_output.$seed.lazy').then((d) => d.Route)
  );

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute;
  '/profile': typeof ProfileRoute;
  '/coderush': typeof CoderushLazyRouteWithChildren;
  '/home': typeof HomeLazyRoute;
  '/login': typeof LoginLazyRoute;
  '/signup': typeof SignupLazyRoute;
  '/coderush/guess_output/$seed': typeof CoderushGuess_outputSeedLazyRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute;
  '/profile': typeof ProfileRoute;
  '/coderush': typeof CoderushLazyRouteWithChildren;
  '/home': typeof HomeLazyRoute;
  '/login': typeof LoginLazyRoute;
  '/signup': typeof SignupLazyRoute;
  '/coderush/guess_output/$seed': typeof CoderushGuess_outputSeedLazyRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexLazyRoute;
  '/profile': typeof ProfileRoute;
  '/coderush': typeof CoderushLazyRouteWithChildren;
  '/home': typeof HomeLazyRoute;
  '/login': typeof LoginLazyRoute;
  '/signup': typeof SignupLazyRoute;
  '/coderush/guess_output/$seed': typeof CoderushGuess_outputSeedLazyRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/profile'
    | '/coderush'
    | '/home'
    | '/login'
    | '/signup'
    | '/coderush/guess_output/$seed';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/profile'
    | '/coderush'
    | '/home'
    | '/login'
    | '/signup'
    | '/coderush/guess_output/$seed';
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/coderush'
    | '/home'
    | '/login'
    | '/signup'
    | '/coderush/guess_output/$seed';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute;
  ProfileRoute: typeof ProfileRoute;
  CoderushLazyRoute: typeof CoderushLazyRouteWithChildren;
  HomeLazyRoute: typeof HomeLazyRoute;
  LoginLazyRoute: typeof LoginLazyRoute;
  SignupLazyRoute: typeof SignupLazyRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/home': {
      id: '/home';
      path: '/home';
      fullPath: '/home';
      preLoaderRoute: typeof HomeLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/coderush': {
      id: '/coderush';
      path: '/coderush';
      fullPath: '/coderush';
      preLoaderRoute: typeof CoderushLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/profile': {
      id: '/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexLazyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/coderush/guess_output/$seed': {
      id: '/coderush/guess_output/$seed';
      path: '/guess_output/$seed';
      fullPath: '/coderush/guess_output/$seed';
      preLoaderRoute: typeof CoderushGuess_outputSeedLazyRouteImport;
      parentRoute: typeof CoderushLazyRoute;
    };
  }
}

interface CoderushLazyRouteChildren {
  CoderushGuess_outputSeedLazyRoute: typeof CoderushGuess_outputSeedLazyRoute;
}

const CoderushLazyRouteChildren: CoderushLazyRouteChildren = {
  CoderushGuess_outputSeedLazyRoute: CoderushGuess_outputSeedLazyRoute,
};

const CoderushLazyRouteWithChildren = CoderushLazyRoute._addFileChildren(
  CoderushLazyRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ProfileRoute: ProfileRoute,
  CoderushLazyRoute: CoderushLazyRouteWithChildren,
  HomeLazyRoute: HomeLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  SignupLazyRoute: SignupLazyRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
